[versions]

#region ---- Kotlin version dependent
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.21"
coroutinesCore = "1.11.0"
#endregion

#region ---- Android Core
agp = "9.2.1"
coreKtx = "1.18.0"
annotation = "1.10.0"
lifecycleRuntimeKtx = "2.10.0"
junit = "4.13.2"
junitVersion = "1.3.0"
mockito = "5.23.0"
robolectric = "4.16.1"
appcompat = "1.7.1"
core = "1.6.1"
#endregion

#region ---- Library/API
mavenPublish = "0.36.0"
#endregion

[libraries]

# build-logic
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
#----- end

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-rules = { module = "androidx.test:rules", version.ref = "core" }
androidx-runner = { module = "androidx.test:runner", version.ref = "core" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore" }

[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

